name: Build LaTeX Document

on:
  push:
    # Décommenter si tu veux déclencher automatiquement sur modification de fichiers LaTeX
    # paths:
    #   - '**.tex'
    #   - '**.sty'
    #   - '**.bib'
    #   - '**.sh'
    #   - '.github/workflows/**'
  workflow_dispatch:

env:
  CHEMIN_PDF: "/home/pviland/00-orgaFormation/webFormation/src/docpdf"

jobs:
  build:
    runs-on: [self-hosted, lblCyber]
    strategy:
      matrix:
        include:
          - folder: act01-installationEnvironnement
            base: act01-installationEnvironnement
          - folder: act02-https
            base: act02-https
          - folder: act03-monitoring
            base: act03-monitoring
          - folder: act04-SNMP
            base: act04-SNMP

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: |
          cd ${{ matrix.folder }}
          chmod +x compilationL.sh
          ls -la
          pwd
          ./compilationL.sh
          ls -la

      - name: Upload artifact E
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.base }}_E
          path: ./${{ matrix.folder }}/${{ matrix.base }}_E.pdf

      - name: Upload artifact P
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.base }}_P
          path: ./${{ matrix.folder }}/${{ matrix.base }}_P.pdf

  copy:
    needs: build
    runs-on: [self-hosted, lblCyber]
    strategy:
      matrix:
        include:
          - folder: act01-installationEnvironnement
            base: act01-installationEnvironnement
          - folder: act02-https
            base: act02-https
          - folder: act03-monitoring
            base: act03-monitoring
          - folder: act04-SNMP
            base: act04-SNMP

    steps:
      - name: Download artifact P
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.base }}_P
          path: ${CHEMIN_PDF}/${{ matrix.base }}

      - name: Download artifact E
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.base }}_E
          path: ${CHEMIN_PDF}/${{ matrix.base }}

      - name: Vérifier que les fichiers sont bien copiés
        run: |
          echo "Contenu de ~/testpdf/${{ matrix.base }} :"
          ls -l ${CHEMIN_PDF}/${{ matrix.base }}
