name: Build LaTeX Document

on:
  push:
    # Décommenter si tu veux déclencher automatiquement sur modification de fichiers LaTeX
    # paths:
    #   - '**.tex'
    #   - '**.sty'
    #   - '**.bib'
    #   - '**.sh'
    #   - '.github/workflows/**'
  workflow_dispatch:

env:
  CHEMIN_PDF: "/home/pviland/00-orgaFormation/webFormation/src/docpdf"
jobs:
  build_1:
    runs-on: [self-hosted, lblCyber]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          cd act01-installationEnvironnement
          ./compilationL.sh

  build_2:
    needs: build_1
    runs-on: [self-hosted, lblCyber]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          cd act02-https
          ./compilationL.sh

  build_3:
    needs: build_2
    runs-on: [self-hosted, lblCyber]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          cd act03-monitoring
          ./compilationL.sh

