name: Build LaTeX Document

on:
  push:
    # Active ceci pour limiter aux fichiers .tex, .sty, etc.
    # paths:
    #   - '**.tex'
    #   - '**.sty'
    #   - '**.bib'
    #   - '**.sh'
    #   - '.github/workflows/**'
  workflow_dispatch:

env:
  CHEMIN_PDF: "/home/pviland/00-orgaFormation/webFormation/src/docpdf"

jobs:
  build_and_copy:
    runs-on: [self-hosted,CyberII]
    strategy:
      matrix:
        include:
        

          - folder: 00-RessourceOrga/r00-git_presentation
            base: r00-git_presentation
            target: 00-RessourceOrga

          - folder: 00-RessourceOrga/r01-dockerPresentation
            base: r01-dockerPresentation
            target: 00-RessourceOrga

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: |
          cd "${{ matrix.folder }}"
          chmod +x compilationL.sh
          ./compilationL.sh
      - name: Copier les PDF générés
        run: |
          DEST="$CHEMIN_PDF/${{ matrix.target }}/${{ matrix.base }}"
          mkdir -p "$DEST"
          cp "${{ matrix.folder }}/${{ matrix.base }}_E.pdf" "$DEST/" || echo "PDF E manquant"
          cp "${{ matrix.folder }}/${{ matrix.base }}_P.pdf" "$DEST/" || echo "PDF P manquant"
      #- name: Zipper et copier le répertoire ressource_eleve (si présent)
      #  run: |
      #    SRC_DIR="${{ matrix.folder }}/ressource_eleve"
      #    DEST_DIR="$CHEMIN_PDF/${{ matrix.target }}/${{ matrix.base }}"
      #    ZIP_NAME="ressource_eleve.zip"
      #    if [ -d "$SRC_DIR" ]; then
      #      mkdir -p "$DEST_DIR"
      #      zip -r "$DEST_DIR/$ZIP_NAME" "$SRC_DIR"
      #    else
      #      echo "Pas de répertoire ressource_eleve à zipper."
      #    fi

      #- name: Vérification finale
      #  run: |
      #    echo "Contenu final de $CHEMIN_PDF/${{ matrix.target }}/${{ matrix.base }} :"
      #    ls -l "$CHEMIN_PDF/${{ matrix.target }}/${{ matrix.base }}"
