name: Build LaTeX Document

on:
  push:
    # Active ceci pour limiter aux fichiers .tex, .sty, etc.
    # paths:
    #   - '**.tex'
    #   - '**.sty'
    #   - '**.bib'
    #   - '**.sh'
    #   - '.github/workflows/**'
  workflow_dispatch:

env:
  CHEMIN_PDF: "/home/pviland/00-orgaFormation/webFormation/src/docpdf"

jobs:
  build_and_copy:
    runs-on: [self-hosted, lblCyber]
    strategy:
      matrix:
        include:
          - folder: act01-installationEnvironnement
            base: act01-installationEnvironnement
            target: 01-syteme

          - folder: act02-https
            base: act02-https
            target: 01-syteme

          - folder: act03-monitoring
            base: act03-monitoring
            target: 01-syteme

          - folder: act04-SNMP
            base: act04-SNMP
            target: 01-syteme

          - folder: act05-gestionLog
            base: act05-gestionLog
            target: 01-syteme

          - folder: act06-Wifi/_SeqIntro-ZenithCiel
            base: _SeqIntro-ZenithCiel
            target: 02-wifi

          - folder: act06-Wifi/act00-EBIOS_Riskmanager
            base: act00-EBIOS_Riskmanager
            target: 02-wifi

          - folder: act06-Wifi/act01-attaqueWifi
            base: act01-attaqueWifi
            target: 02-wifi

          - folder: act06-Wifi/act02-authentificationDevice
            base: act02-authentificationDevice
            target: 02-wifi

          - folder: act06-Wifi/act03-dumpDevice
            base: act03-dumpDevice
            target: 02-wifi

          - folder: 00-RessourceOrga/r00-git_presentation
            base: r00-git_presentation
            target: 00-RessourceOrganisation

          - folder: 00-RessourceOrga/r01-dockerPresentation
            base: r01-dockerPresentation
            target: 00-RessourceOrganisation
            
          - folder: 00-RessourceOrga/p00-presentationAct
            base: p00-presentationAct
            target: 00-RessourceOrganisation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: |
          cd "${{ matrix.folder }}"
          chmod +x compilationL.sh
          ./compilationL.sh

      - name: Copier les PDF générés
        run: |
          DEST="$CHEMIN_PDF/${{ matrix.target }}/${{ matrix.base }}"
          mkdir -p "$DEST"
          cp "${{ matrix.folder }}/${{ matrix.base }}_E.pdf" "$DEST/" || echo "PDF E manquant"
          cp "${{ matrix.folder }}/${{ matrix.base }}_P.pdf" "$DEST/" || echo "PDF P manquant"

      - name: Zipper et copier le répertoire ressource_eleve (si présent)
        run: |
          SRC_DIR="${{ matrix.folder }}/ressource_eleve"
          DEST_DIR="$CHEMIN_PDF/${{ matrix.target }}/${{ matrix.base }}"
          ZIP_NAME="ressource_eleve.zip"
          if [ -d "$SRC_DIR" ]; then
            mkdir -p "$DEST_DIR"
            zip -r "$DEST_DIR/$ZIP_NAME" "$SRC_DIR"
          else
            echo "Pas de répertoire ressource_eleve à zipper."
          fi

      - name: Vérification finale
        run: |
          echo "Contenu final de $CHEMIN_PDF/${{ matrix.target }}/${{ matrix.base }} :"
          ls -l "$CHEMIN_PDF/${{ matrix.target }}/${{ matrix.base }}"
