name: Build LaTeX Document

on:
  push:
    # Décommenter si tu veux déclencher automatiquement sur modification de fichiers LaTeX
    # paths:
    #   - '**.tex'
    #   - '**.sty'
    #   - '**.bib'
    #   - '**.sh'
    #   - '.github/workflows/**'
  workflow_dispatch:

env:
  CHEMIN_PDF: "/home/pviland/00-orgaFormation/webFormation/src/docpdf"

jobs:
  build:
    runs-on: [self-hosted, lblCyber]
    strategy:
      matrix:
        include:
          - folder: act01-installationEnvironnement
            base: act01-installationEnvironnement
          - folder: act02-https
            base: act02-https
          - folder: act03-monitoring
            base: act03-monitoring
          - folder: act04-SNMP
            base: act04-SNMP
          - folder: act05-gestionLog
            base: act05-gestionLog
            
          - folder: act06-Wifi/_SeqIntro-ZenithCiel
            base: _SeqIntro-ZenithCiel
      
          - folder: act06-Wifi/act00-EBIOS_Riskmanager
            base: act00-EBIOS_Riskmanager
      
          - folder: act06-Wifi/act01-attaqueWifi
            base: act01-attaqueWifi
      
          - folder: act06-Wifi/act02-authentificationDevice
            base: act02-authentificationDevice
      
          - folder: act06-Wifi/act03-dumpDevice
            base: act03-dumpDevice


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile LaTeX document
        run: |
          cd ${{ matrix.folder }}
          chmod +x compilationL.sh
          ls -la
          pwd
          ./compilationL.sh
          ls -la
      - name: Lister les fichiers PDF générés
        run: |
          echo "Liste des fichiers PDF dans ${{ matrix.folder }} :"
          find ${{ matrix.folder }} -name '*.pdf'

      - name: Upload artifact E
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.base }}_E
          path: ./${{ matrix.folder }}/${{ matrix.base }}_E.pdf

      - name: Upload artifact P
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.base }}_P
          path: ./${{ matrix.folder }}/${{ matrix.base }}_P.pdf

  copy:
    needs: build
    runs-on: [self-hosted, lblCyber]
    strategy:
      matrix:
        include:
          - folder: act01-installationEnvironnement
            base: act01-installationEnvironnement
          - folder: act02-https
            base: act02-https
          - folder: act03-monitoring
            base: act03-monitoring
          - folder: act04-SNMP
            base: act04-SNMP
          - folder: act05-gestionLog
            base: act05-gestionLog

    steps:
      - name: Download artifact P
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.base }}_P
          path: ${{ env.CHEMIN_PDF }}/${{ matrix.base }}

      - name: Download artifact E
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.base }}_E
          path: ${{ env.CHEMIN_PDF }}/${{ matrix.base }}

      - name: Vérifier que les fichiers sont bien copiés
        run: |
          echo "Contenu de $CHEMIN_PDF/${{ matrix.base }} :"
          ls -l "$CHEMIN_PDF/${{ matrix.base }}"


  copyWifi:
    needs: build
    runs-on: [self-hosted, lblCyber]
    strategy:
      matrix:
        include:
          
          - folder: act06-Wifi/_SeqIntro-ZenithCiel
            base: _SeqIntro-ZenithCiel
      
          - folder: act06-Wifi/act00-EBIOS_Riskmanager
            base: act00-EBIOS_Riskmanager
      
          - folder: act06-Wifi/act01-attaqueWifi
            base: act01-attaqueWifi
      
          - folder: act06-Wifi/act02-authentificationDevice
            base: act02-authentificationDevice
      
          - folder: act06-Wifi/act03-dumpDevice
            base: act03-dumpDevice
    steps:
      - name: Download artifact P
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.base }}_P
          path: ${{ env.CHEMIN_PDF }}/wifi/${{ matrix.base }}

      - name: Download artifact E
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.base }}_E
          path: ${{ env.CHEMIN_PDF }}/wifi/${{ matrix.base }}

      - name: Vérifier que les fichiers sont bien copiés
        run: |
          echo "Contenu de $CHEMIN_PDF/wifi/${{ matrix.base }} :"
          ls -l "$CHEMIN_PDF/wifi/${{ matrix.base }}"
      - name: Copier le répertoire ressource_eleve
        run: |
          SRC_DIR="${{ matrix.folder }}/ressource_eleve"
          DEST_DIR="$CHEMIN_PDF/wifi/${{ matrix.base }}/ressource_eleve"
          
          if [ -d "$SRC_DIR" ]; then
            echo "Copie de $SRC_DIR vers $DEST_DIR"
            mkdir -p "$DEST_DIR"
            cp -r "$SRC_DIR/"* "$DEST_DIR"
          else
            echo "Le répertoire $SRC_DIR n'existe pas, rien à copier."
          fi
